schemaVersion: 2.1.0
metadata:
  name: puppet-autofs
  displayName: Puppet AutoFS
components:
  - name: tools
    container:
      image: quay.io/ludovicus/pdk-developer-image:ubi8
      memoryLimit: 2Gi
      memoryRequest: 256Mi
commands:
  - id: update-pdk
    exec:
      commandLine: pdk update --force
      component: tools
      label: Update PDK Files
      workingDir: ${PROJECT_SOURCE}
events:
  postStart:
    - update-pdk
