schemaVersion: 2.1.0
metadata:
  name: puppet-autofs
  displayName: Puppet AutoFS
components:
  - name: tools
    container:
      image: quay.io/ludovicus/pdk-developer-image:latest
      memoryLimit: 2Gi
      memoryRequest: 256Mi
commands:
  - id: pdk-update
    exec:
      commandLine: pdk update
      component: tools
      label: Update PDK Files
      workingDir: ${PROJECT_SOURCE}
  - id: pdk-bundle-install
    exec:
      commandLine: pdk bundle install
      component: tools
      label: Install Bundled Dependencies
      workingDir: ${PROJECT_SOURCE}
